<img src="img/itq.jpg" style="width:90px;"> <br>
<h2 style="font-family: 'Times New Roman', Times, serif; text-align: center;">PAO25_26_25_Python_Normalizacion</h2>
<h2 style="font-family: 'Times New Roman', Times, serif; text-align: center;">Marzo 25, 2026</h2>
<p style="font-family: 'Times New Roman', Times, serif; font-weight:bold; font-size:16px;">
</p>

<img src="img/img2.png" alt="imagen" style="display:block; margin: 0 auto;"> </br>

*Bryan Antamba y Esteban Sanchez*

<div style="font-family: 'Times New Roman', Times, serif;">
    
## **Normalizacion**
</div>

In [1]:
from sklearn import preprocessing
import numpy as np

In [2]:
# Carga de datos.
X_train = np.array([[ 1., -4.,  5.],
                    [ 5.,  0.,  2.],
                    [ 0.,  6., -3.]])

print(X_train)

[[ 1. -4.  5.]
 [ 5.  0.  2.]
 [ 0.  6. -3.]]


In [3]:
# Limpieza de datos: normalización.
normalizer = preprocessing.MinMaxScaler()
X_train_norm = normalizer.fit_transform(X_train)

In [4]:
# Salida de resultados.
print(X_train_norm)

[[0.2   0.    1.   ]
 [1.    0.4   0.625]
 [0.    1.    0.   ]]


In [5]:
# Ejemplo para ver que los resultados son iguales si aplicamos los métodos "fit" y "transform" por separado
X_train_2 = np.copy(X_train)

# Crea un objeto "fitted_normalizer" llamando al método "fit"
f = normalizer.fit(X_train)

# Aplica el objeto sobre los datos "X_train_2" para obtener "X_train_norm_2"
X_train_norm_2 = f.transform(X_train)

# Comprueba si "X_train_norm" y "X_train_norm_2" son iguales
print(np.array_equiv(X_train_norm, X_train_norm_2))

True


In [6]:
x_test = np.array([[1., -3., 2.],
                   [3., 0., 0.],
                   [0., 4., -1.]])
print(x_test)

[[ 1. -3.  2.]
 [ 3.  0.  0.]
 [ 0.  4. -1.]]


In [7]:
x_test_norm = normalizer.transform(x_test)
print(x_test_norm)

[[0.2   0.1   0.625]
 [0.6   0.4   0.375]
 [0.    0.8   0.25 ]]
