<img src="../img/itq.jpg" style="width:90px;"> <br>
<h2 style="font-family: 'Times New Roman', Times, serif; text-align: center;">PAO25_26_29_Python_Numpy</h2>
<h2 style="font-family: 'Times New Roman', Times, serif; text-align: center;">Enero 16, 2026</h2>
<p style="font-family: 'Times New Roman', Times, serif; font-weight:bold; font-size:16px;">
0.1 PAO25-26- Numpy
</p>

<img src="../img/img2.png" alt="imagen" style="display:block; margin: 0 auto;"> </br>

*Bryan Justin Antamba*
<div style="font-family: 'Times New Roman', Times, serif;">
    
## **1 Numpy ndarray**

* NumPy (**Num** erical **Py** thon) es la de facto librería estándar para análisis numérico en Python.
* Estructura de datos multidimensional eficiente (escrita en C): ndarray
* Colección de funciones para álgebra lineal, estadística descriptiva
* Ayuda al procesamiento de datos (np.where)
</div>

In [1]:
#importar libreria
import numpy as np

<div style="font-family: 'Times New Roman', Times, serif;">
    
#### **1.1 Performance Sample, NumPy vs Plain Python**
</div>

In [2]:
my_list = list(range(10000000)) # Utilizando Listas Python
%time my_list = [x * 2 for x in my_list]

CPU times: total: 547 ms
Wall time: 549 ms


In [3]:
my_arr = np.arange(10000000) # Utilizando NumPy Arrays
%time my_arr2 = my_arr * 2

CPU times: total: 15.6 ms
Wall time: 15.8 ms


<div style="font-family: 'Times New Roman', Times, serif;">
    
#### **1.2 Formas de crear ndarrays**
</div>

In [4]:
array = np.array([ [2,71,0,34], [2,171,-35,34] ]) # 2D
print(array)

[[  2  71   0  34]
 [  2 171 -35  34]]


In [5]:
shopping_list = [ ['onions', 'carrots', 'celery'], ['apples', 'oranges','grapes'] ] # 2D
array = np.array(shopping_list) # convertir una lista en una ndarray
print(array)
print(type(array))

[['onions' 'carrots' 'celery']
 ['apples' 'oranges' 'grapes']]
<class 'numpy.ndarray'>


In [6]:
print(np.array([100,10,1])) # array a partir de una lista
print(np.arange(2,10,2.1)) # array a partir de una secuencia(range) 1D

[100  10   1]
[2.  4.1 6.2 8.3]


In [7]:
# Generar arrays con valores fijos
print(np.zeros(2))
# 1D
print(np.ones((4,3)))
# matrix 2x2
print(np.empty((2,2,2))) # matrix 2x2x2, no inicializados
print(np.full((5,2),2)) # matrix 5x2
print(np.eye(3)) # matrix identity

[0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[[9.88e-324 3.51e-322]
  [0.00e+000 1.68e-322]]

 [[9.88e-324 8.45e-322]
  [      nan 1.68e-322]]]
[[2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<div style="font-family: 'Times New Roman', Times, serif;">
    
#### **1.3 Obtener información sobre ndarray**
</div>

In [8]:
my_ndarray = np.array([2,71,0,34])
print(my_ndarray)

[ 2 71  0 34]


In [9]:
print(my_ndarray.argmax()) # índice del valor más alto
print(np.amax(my_ndarray))
print(my_ndarray.argmin()) # índice del valor más bajo
print(np.amin(my_ndarray))
print(my_ndarray.nonzero()) # retorna los índices de los elementos distintos␣ a 0

1
71
2
0
(array([0, 1, 3]),)


In [10]:
my_ndarray = np.full((5, 4,2), 2) # matrix 5x2x2
print(my_ndarray)
print(my_ndarray.size) # número de elementos
print(my_ndarray.shape) # dimensiones
print(my_ndarray.ndim) # número de dimensiones

[[[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]

 [[2 2]
  [2 2]
  [2 2]
  [2 2]]]
40
(5, 4, 2)
3


In [11]:
my_ndarray = np.array([2,71,0,34])
print(my_ndarray.size) # número de elementos
print(my_ndarray.shape) # dimensiones
print(my_ndarray.ndim) # número de dimensiones

4
(4,)
1


<div style="font-family: 'Times New Roman', Times, serif;">
    
**Redimensionar los datos**
</div>

In [12]:
my_ndarray = np.array([[0, 71, 21, 19, 213, 412, 111, 98]]) # matrix 1x8
print(my_ndarray)
print(my_ndarray.shape)
print(my_ndarray.ndim)

[[  0  71  21  19 213 412 111  98]]
(1, 8)
2


In [13]:
new_dims = my_ndarray.reshape(2, 4) # cambiar las dimensiones a 2x4
print(new_dims)
print(new_dims.ndim)

[[  0  71  21  19]
 [213 412 111  98]]
2


In [14]:
new_dims = my_ndarray.reshape(4, 2) # cambiar las dimensiones a 4x2
print(new_dims)
print(new_dims.ndim)

[[  0  71]
 [ 21  19]
 [213 412]
 [111  98]]
2


In [15]:
x = np.array([100, 10, 1]).reshape(3,1)
print(x.shape)
print(x)

(3, 1)
[[100]
 [ 10]
 [  1]]


In [16]:
# reducir a 1D
new_dims = np.arange(9).reshape(3,3)
print(new_dims)
print(new_dims.flatten())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [17]:
# reducir
new_dims = np.arange(16).reshape(4,4)
print(new_dims)
print(new_dims.reshape(2,-1)) # el segundo valor se infiere del primero

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


<div style="font-family: 'Times New Roman', Times, serif;">
    
#### **1.4 Manipulación de ndarrays**
</div>

In [18]:
# Cambiar ejes
new_dims = np.arange(16).reshape(8,2)
print(new_dims)
print(new_dims.swapaxes(0,1))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[ 0  2  4  6  8 10 12 14]
 [ 1  3  5  7  9 11 13 15]]


In [19]:
# Flip
new_dims = np.arange(16).reshape(4,4)
print(new_dims)
print(np.flip(new_dims, axis = None))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [20]:
# ordenar
array1 = np.array([10,2,9,17])
array1.sort()
print(array1)

[ 2  9 10 17]


In [21]:
# Juntar dos arrays
a1 = [0,0,0,0,0,0]
a2 = [1,1,1,1,1,1]
print(np.hstack((a1,a2))) # una al lado de la otra
print(np.hstack((a1,a2)).shape)
print(np.vstack((a1,a2))) # una encima de la otra
print(np.vstack((a1,a2)).shape)

[0 0 0 0 0 0 1 1 1 1 1 1]
(12,)
[[0 0 0 0 0 0]
 [1 1 1 1 1 1]]
(2, 6)


In [22]:
array1 = np.array([[2, 4], [6, 8]])
array2 = np.array([[3, 5], [7, 9]])
print(np.concatenate((array1, array2), axis = 0))

[[2 4]
 [6 8]
 [3 5]
 [7 9]]


In [23]:
# dividir un array
array = np.arange(16).reshape(4,4)
print(array)
print(np.array_split(array, 2, axis = 0)) # divide array en 2 partes iguales
print(np.array_split(array, 3)) # divide array en 3 partes "iguales"

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [24]:
# dividir un array
array = np.arange(16).reshape(4,4)
print(array)
print(np.array_split(array, [3], axis = 1)) # divide array, por la fila 3

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [25]:
split = np.array_split(array, [3], axis = 1)
print(split[0][3][0])

12


In [26]:
array = np.arange(64).reshape(8,8)
print(array)
print(np.array_split(array, [1, 3], axis = 0)) # divide array por la fila 1 y 3
print(np.array_split(array, [1, 3], axis = 1)) # divide array por la columna 1␣ y 3
# axis = n_dimensions- 1

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])]
[array([[ 0],
       [ 8],
       [16],
       [24],
       [32],
       [40],
       [48],
       [56]]), array([[ 1,  2],
       [ 9, 10],
       [17, 18],
       [25, 26],
       [33, 34],
       [41, 42],
       [49, 50],
       [57, 58]]), array([[ 3,  4,  5,  6,  7],
       [11, 12, 13, 14, 15],
       [19, 20, 21, 22, 23],
       [27, 28, 29, 30, 31],
       [35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55],
       [

<div style="font-family: 'Times New Roman', Times, serif;">
    
## **2  Índices y slicing**

* De manera análoga a índices y slicing para listas
</div>

In [27]:
array = np.arange(10, 16)
print(array)
print(array[-1]) # acceso unidimensional
print(array[:-1]) # slice

[10 11 12 13 14 15]
15
[10 11 12 13 14]


In [28]:
# bidimensional
array = np.arange(16).reshape(4,4)
print(array)
print(array[2, 2]) # fila, columna
print(array[3][2]) # fila, columna

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
10
14


In [29]:
# multidimensional
array = np.arange(36).reshape(2,3,6)
print(array)
print(array[0,2,4])
print(array[1][2][4])

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]
16
34


<div style="font-family: 'Times New Roman', Times, serif;">
    
**NumPy es row major**
</div>

In [30]:
row_major = np.array([1, 2, 3, 4, 5, 6])
row_major = row_major.reshape(2,3) # by default, row major
print(row_major)

[[1 2 3]
 [4 5 6]]


In [31]:
row_major = np.array([1, 2, 3, 4, 5, 6])
row_major = row_major.reshape(2,3,order='C') # by default, row major
print(row_major)
col_major = np.array([1, 2, 3, 4, 5, 6])
col_major = col_major.reshape(2,3,order='F') # col major
print(col_major)

[[1 2 3]
 [4 5 6]]
[[1 3 5]
 [2 4 6]]


<div style="font-family: 'Times New Roman', Times, serif;">
    
**Slice**
</div>

In [32]:
# se puede hacer slice por fila o columna
array = np.arange(81).reshape(9,9)
print(array)
print(array[1:3, 2::2])

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]]
[[11 13 15 17]
 [20 22 24 26]]


In [33]:
# se puede hacer slice por fila o columna
array = np.arange(9).reshape(3,3)
print(array)
print(array[0,:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


<div style="font-family: 'Times New Roman', Times, serif;">
    
**Diferencias entre índices y slicing en listas y ndarrays:**

* ¡Retornan una referencia, no una copia!
</div>

In [34]:
# uso de slice en listas, retorna copia
lista = [0,1,2,3,4,5,6,7,8,9]
my_copy = lista[0:2] # devuelve una copia
print(my_copy)
my_copy[0] = 222
print(lista)
print(my_copy)

[0, 1]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[222, 1]


In [35]:
# slicing retorna una referencia en ndarrays
array = np.arange(10)
my_copy = array[2:5] # devuelve una referencia
print(array)
print(my_copy)
my_copy[0] = 222
print(array)
print(my_copy)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[  0   1 222   3   4   5   6   7   8   9]
[222   3   4]


In [36]:
# copiar ndarrays
array = np.arange(10)
my_copy = array[2:5].copy() # hay que hacer la copia explicitamente
my_copy[0] = 222
print(array)
print(my_copy)

[0 1 2 3 4 5 6 7 8 9]
[222   3   4]


<div style="font-family: 'Times New Roman', Times, serif;">  

* Permite asignar valores a un corte.
</div>

In [37]:
array = np.arange(10)
print(array)
print(array[0:3])
array[0:3] =-1
print(array)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[-1 -1 -1  3  4  5  6  7  8  9]


<div style="font-family: 'Times New Roman', Times, serif;">  

* Slicing condicionales (mask).
</div>

In [38]:
# slicing condicional
array = np.arange(-3,4)
print(array)
mask = array %2 == 0
print(mask)
print(array[mask])
print(array[array %2 == 0])
array[mask] = 0
print(array)

[-3 -2 -1  0  1  2  3]
[False  True False  True False  True False]
[-2  0  2]
[-2  0  2]
[-3  0 -1  0  1  0  3]


In [39]:
array = np.arange(-3,4)
print(array)

array[array < 0] = 0
print(array)

[-3 -2 -1  0  1  2  3]
[0 0 0 0 1 2 3]


In [40]:
# slicing condicional
array = np.arange(-3,4)
print(array)
mask = array % 2 == 0
print(mask)
array_par = array[mask] # devuelve una copia
print(array_par)
array_par[0] =-10
print(array)
print(array_par)

[-3 -2 -1  0  1  2  3]
[False  True False  True False  True False]
[-2  0  2]
[-3 -2 -1  0  1  2  3]
[-10   0   2]


<div style="font-family: 'Times New Roman', Times, serif;">  

* Acceso a múltiples valores con listados de índices.
</div>

In [41]:
array = np.arange(0,16).reshape(4,4)
print(array)
print(array[[1,2]]) #selecting rows
print(array[:,[1,2]]) #selecting columns
# cross product of indexes
print(array[[1,2],:][:,[1,2]])
print(array[np.ix_([1,2],[1,2])]) # built in ix_
ar = array[[2,3,1]] # slice, copia
print(ar)
ar[0] = 999
print(ar)
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 5  6]
 [ 9 10]]
[[ 5  6]
 [ 9 10]]
[[ 8  9 10 11]
 [12 13 14 15]
 [ 4  5  6  7]]
[[999 999 999 999]
 [ 12  13  14  15]
 [  4   5   6   7]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


<div style="font-family: 'Times New Roman', Times, serif;">
    
## **3 Funciones matemáticas**

*  Aplicar operaciones entre escalares y arrays o entre arrays.
</div>

In [42]:
# listas y escalares
lista = [0,1,2,3]
lista *= 3
print(lista)

lista += [1]
print(lista)

[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]
[0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 1]


In [43]:
# ndarray hace las operaciones sobre los elementos
array = np.ones(4, dtype = np.int8)
print(array)
array *= 2
print(array)

array += 10
print(array)

print(array.dtype) # check data type of array

[1 1 1 1]
[2 2 2 2]
[12 12 12 12]
int8


In [44]:
# operaciones entre arrays es como operaciones entre matrices
array_1 = np.ones(4) * 2
array_2 = np.arange(4) + 1

print(array_1)
print(array_2)

print(array_1 + array_2)
print(array_1- array_2)
print(array_1 * array_2)
print(array_2 / array_1)

[2. 2. 2. 2.]
[1 2 3 4]
[3. 4. 5. 6.]
[ 1.  0. -1. -2.]
[2. 4. 6. 8.]
[0.5 1.  1.5 2. ]


<div style="font-family: 'Times New Roman', Times, serif;">
    
#### **3.1 Broadcasting**

Si las arrays no tienen las mismas dimensiones, se hace broadcast del pequeño al grande-> <a href="https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html">broad-casting</a>

#### **3.2 Operadores unarios y binarios**
</div>

<div style="font-family: 'Times New Roman', Times, serif;">

| Tipo | Operacion|Descripcion
|----------|-----|:----------:|
|| *arccos, arcsin, arctan*| Inversas de operacionestrigonométricas en cada  Selemento
|Binario| Resta | *dd substract multiply*| Suma de dos arrays Resta de dos arrays Multiplicación de dos arrays
||divide maximum, minimum| División de dos arrays Retorna el valor máximo/mínimo de cada pareja de elementos
||*qual, not_equal*| Retorna la comparación (igual o no igual) de cada pareja de elementos
||*greater, greater_equal,less, less_equal*| Retorna la comparación (>, >=, <, <= respectivamente) de cada pareja de elementos
</div>

In [45]:
# ejemplos de operadores
array = np.arange(5)
print(array)
np.sqrt(array)

[0 1 2 3 4]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [46]:
# ejemplos de operadores
array1 = np.arange(4)
array2 = np.array([0,-1,2,-3])
print(array1)
print(array2)
print(np.greater(array1,array2))
print(np.less(array2, array1))

[0 1 2 3]
[ 0 -1  2 -3]
[False  True False  True]
[False  True False  True]


<div style="font-family: 'Times New Roman', Times, serif;">
    
## **4 Estadística descriptiva**

* Importante saber la naturaleza de los datos
* Valores máximos, mínimos, distribución, etc.
</div>

<div style="font-family: 'Times New Roman', Times, serif;">

| fUNCION |Descripcion
|----------|:----------:|
| *Sum(arr)*| Suma de todos los elementos de arr
|*mean(arr)*| Media aritmética de los elementos de arr
| *std(arr)* | Desviación estándar de los elementos de arr
|*cumsum(arr)*| Devuelve array con la suma acumulada de cada elementos con todos los anteriores
|*cumprod(arr)*| Devuelve array con el producto acumulado de cada elementos con todos los anteriores
|*min(arr), max(arr)*| Mínimo y máximo de arr
|*any(arr)*| En array de tipo bool, retorna *True* si algún elemento es *True*
|*all(arr)*| En array de tipo bool, retorna *True* si todos los elementos son *True* (o <>0 en valores numéricos)
|*unique(arr)*| Devuelve un array con valores únicos
|*in1d(arr1, arr2)*| Devuelve un array con bool indicando si cada elemento de arr1 está en arr2
|*union1d(arr1, arr2)*|Devuelve la unión de ambos arrays
|*intersect1d(arr1,arr2)*| Devuelve la intersección de ambos arrays
</div>

In [47]:
# sum != cumsum
array1 = np.arange(9)
print(array1)
print(array1.sum())
print(array1.cumsum())

[0 1 2 3 4 5 6 7 8]
36
[ 0  1  3  6 10 15 21 28 36]


In [48]:
# any vs all
array1 = np.arange(-8,2).reshape(2,5)
print(array1)
print(array1.any()) # any para saber si hay elementos True o valores <> 0
print(array1.all()) # all para saber si TODOS los elementos son True o valores <> 0

[[-8 -7 -6 -5 -4]
 [-3 -2 -1  0  1]]
True
False


In [49]:
# todas las funciones aceptan parametro 'axis'
# 0 para columnas, 1 para filas, 2 para profundidad...
array1 = np.arange(10).reshape(2,5)
print(array1)
print(array1.all(axis=0))
print(array1.all(axis=1))
print(array1.all())

[[0 1 2 3 4]
 [5 6 7 8 9]]
[False  True  True  True  True]
[False  True]
False


<div style="font-family: 'Times New Roman', Times, serif;">
    
## **5 Algebra lineal**

* numpy.linalg contiene funciones para álgebra lineal
* dot product, multiplicación de matrices, cálculo del determinante, factorizaciones…
</div>

<div style="font-family: 'Times New Roman', Times, serif;">

| fUNCION |Descripcion
|----------|:----------:|
|*dot(mat1, mat2)*| Devuelve el producto escalar entre dos arrays. Si son matrices 2D, es equivalente a la multiplicación de ambas
|*matmul(mat1, mat2)*| Devuelve el producto entre dos matrices
|*trace(mat1, mat2)*| Suma de las diagonales de ambas matrices
|*det(mat)*| Devuelve el determinante de la matriz
|*eig(mat)*| Computa los autovalores y autovectores de la matriz cuadrada mat
|*inv(mat)*| Devuelve la inversa de la matriz
|*qr(mat)*| Computa la factorización QR de mat
|*solve(A, b)*|Resuelve el sistema lineal de ecuaciones Ax = b para b, cuando A es una matriz cuadrada
|*transpose(mat)*| Devuelve la transpuesta de la matrix
</div>

In [50]:
A = np.arange(12).reshape(4,3)
B = np.arange(6).reshape(3,2)

print(A)
print(B)

print(np.matmul(A, B))
print(np.dot(A, B))
print(A @ B)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 1]
 [2 3]
 [4 5]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]
[[10 13]
 [28 40]
 [46 67]
 [64 94]]


In [51]:
import numpy.linalg as lg
import math
# resolver sistema de ecuaciones
# 3x + 2y + 5z = 12
# x- 3y-z = 2
# 2x-y +12z = 32
# Ax = b--> resolver para x

a = np.array([ [3,2,5], [1,-3,-1], [2,-1,12] ])
b = np.array([12,2,32])

print(a)
print(b)
x,y,z = lg.solve(a,b)
print(f'x={x} y={y} z={z}')

print(math.isclose(3*x + 2*y +5*z, 12))
print(math.isclose(x- 3*y- z, 2))
print(math.isclose(2*x-y + 12*z, 32))

[[ 3  2  5]
 [ 1 -3 -1]
 [ 2 -1 12]]
[12  2 32]
x=0.7543859649122807 y=-1.2280701754385965 z=2.43859649122807
True
True
True


In [52]:
#matriz identidad
I = np.identity(4)
print(I)
A = np.arange(16).reshape(4,4)
print(A)
print(np.matmul(A,I))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


<div style="font-family: 'Times New Roman', Times, serif;">
    
## **6 Filtrado de datos**

* Filtrar y modificar datos numéricos con np.where
* Retorna A o B en función de una condición en una array
</div>

In [53]:
prices = np.array([0.99, 14.49, 19.99, 20.99, 0.49])
mask = prices < 1
print(prices[prices < 1]) #slicing condicional
# mask con los elementos menores de 1
mask = np.where(prices < 1, True, False)
print(mask)
print(prices[mask])
prices[mask] = 1.0
print(prices)
print(np.where(prices < 1, 1.0, prices))

[0.99 0.49]
[ True False False False  True]
[0.99 0.49]
[ 1.   14.49 19.99 20.99  1.  ]
[ 1.   14.49 19.99 20.99  1.  ]


In [54]:
# Se puede usar para sustituir datos fuera de rango
bank_transfers_values = np.array([0.99,-1.49, 19.99, 20.99,-0.49, 12.1]).reshape(2, 3)
print(bank_transfers_values)
clean_data = np.where(bank_transfers_values > 0, bank_transfers_values, 0)
print(clean_data)

[[ 0.99 -1.49 19.99]
 [20.99 -0.49 12.1 ]]
[[ 0.99  0.   19.99]
 [20.99  0.   12.1 ]]


In [55]:
# limpiar NaN (sustitución)
data = [10, 12,-143, np.nan, 1,-3] # np.nan--> NotANumber, elemento especial
data_clean = np.where(np.isnan(data), 0, data)
print(data_clean)

print(id(data))
print(id(data_clean))

[  10.   12. -143.    0.    1.   -3.]
1800455434240
1800457358960


In [56]:
# np.where puede seleccionar elementos
bank_transfers_values = np.array([0.99,-1.49, 19.99, 20.99,-0.49, 12.1]).reshape(2, 3)
print(bank_transfers_values)
credits = np.where(bank_transfers_values > 0) # array de índices para los que␣la condición es True
print(credits)
print(bank_transfers_values[credits]) # es igual que␣bank_transfers_values[bank_transfers_values > 0]
print(bank_transfers_values[bank_transfers_values > 0])

[[ 0.99 -1.49 19.99]
 [20.99 -0.49 12.1 ]]
(array([0, 0, 1, 1]), array([0, 2, 0, 2]))
[ 0.99 19.99 20.99 12.1 ]
[ 0.99 19.99 20.99 12.1 ]


In [57]:
# valor de array dependiendo del valor en array referencia
rewards_default = np.arange(6)
print(rewards_default)
rewards_upgrade = np.arange(6) * 10
print(rewards_upgrade)
daily_points = np.array([0, 0, 1, 6, 0, 2])
print(daily_points)
final_rewards = np.where(daily_points > 1, rewards_upgrade, rewards_default)
print(final_rewards)

[0 1 2 3 4 5]
[ 0 10 20 30 40 50]
[0 0 1 6 0 2]
[ 0  1  2 30  4 50]


<div style="font-family: 'Times New Roman', Times, serif;">
    
## **7 Números aleatorios**

* Python módulo random
</div>

In [58]:
import random

print(random.random()) # número entre 0 y 1
print(random.randint(0,5)) # integral entre dos valores
print(random.uniform(0,5)) # real entre dos valores

0.4589416732943219
5
4.482328261352813


In [59]:
# elegir un elemento al azar dentro de una colección
names = ['Pikachu','Eevee','Charmander']
random.choice(names)

'Charmander'

<div style="font-family: 'Times New Roman', Times, serif;">
    
#### **7.1 NumPy.random**

* Generar fácilmente listas con valores aleatorios
</div>

In [60]:
print(np.random.rand()) # número entre 0 y 1
print(np.random.randint(0,5)) # integral entre dos valores
print(np.random.randint(5, size=(2, 4))) # parametro 'size' para indicar las dimensiones)

0.573798927661574
0
[[0 3 3 3]
 [0 1 4 0]]


In [61]:
# array de elementos aleatorios (distribucion normal gaussiana, media 0, desviación 1)
print(np.random.randn(4,2))

[[-2.01700341  1.38637289]
 [-0.17811649 -1.05338721]
 [ 0.67366928  0.09460836]
 [-0.45906836  2.35260049]]


In [62]:
# otras distribuciones
print(np.random.binomial(n=5, p=0.3)) # 'n' intentos, 'p' probabilidad
print(np.random.uniform(low=0, high=10)) # distribución uniforme
print(np.random.poisson(lam=2, size=(2,2))) # 'lam' número de ocurrencias␣ esperadas, retornar 'size' valores

2
6.9036050262210145
[[2 7]
 [2 5]]


<div style="font-family: 'Times New Roman', Times, serif;">
    
#### **7.2 Random seed**
* Números pseudo-aleatorios
* Ordenadores generan números a partir de ecuaciones
* Basadas en un número inicial (seed)
* Bueno para reproducibilidad de experimentos
</div>

In [63]:
i = 5
for _ in range(5):
    np.random.seed(i) # misma semilla
    print(np.random.rand())
    print(np.random.rand())
print()

for i in range(6):
    np.random.seed(i) # diferentes semillas
    print(np.random.rand())
    print(np.random.rand())

0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764
0.22199317108973948
0.8707323061773764

0.5488135039273248
0.7151893663724195
0.417022004702574
0.7203244934421581
0.43599490214200376
0.025926231827891333
0.5507979025745755
0.7081478226181048
0.9670298390136767
0.5472322491757223
0.22199317108973948
0.8707323061773764


<div style="font-family: 'Times New Roman', Times, serif;">
    
## **8 Escritura y lectura de ndarrays a archivos**

* Para futuro acceso
* Compartir datos con otros
* Formato *.npy
</div>

In [64]:
# escribir a archivo
import os
ruta = os.path.join("res" ,"o_values_array.npy")

values = np.random.randint(9, size=(3,3))
np.save(ruta, values)
print(values)

[[6 6 0]
 [8 4 7]
 [0 0 7]]


In [65]:
# leer de archivo
old_values = np.load(ruta)
print(old_values)

[[6 6 0]
 [8 4 7]
 [0 0 7]]


In [66]:
# escribir y cargar múltiples arrays
ruta = os.path.join("res" ,"o_array_group.npz")
values1 = np.random.randint(9,size=(3,3))
values2 = np.random.randint(4,size=(2,2))
values3 = np.random.randint(16,size=(4,4))
np.savez(ruta,values1,values2,values3) # añade la extensión .npz

In [67]:
# leer los archivos (retorna un diccionario con las arrays)
npzfile = np.load(ruta)

print(type(npzfile.files))
print(npzfile.files)

for key in npzfile.files: # array.files contiene el nombre de las arrays␣ (arr_0, arr_1...)
     print(npzfile[key])

<class 'list'>
['arr_0', 'arr_1', 'arr_2']
[[1 5 7]
 [0 1 4]
 [6 2 1]]
[[2 3]
 [0 2]]
[[ 5 10  0  0]
 [ 4 14  4  9]
 [ 3 11 15  2]
 [ 4  6  9  3]]


<div style="font-family: 'Times New Roman', Times, serif;">
    
#### **8.0.1 ¿Por qué molestarse con .npy?**
* Bases de datos suelen estar en CSV o txt, que requieren lectura con streams (parsing)
* ¿Para qué escribir los datos de nuevo?
</div>

In [68]:
import numpy as np

data = np.random.randint(0, 10, size=(1000, 1000))
data.flatten().tofile("res/fdata.csv", sep=",")

In [69]:
import os
ruta_csv = os.path.join("res" ,"fdata.csv")
with open(ruta_csv,'r') as f:
     data_str = f.read()
data = data_str.split(',')
data_array = np.array(data, dtype = np.int8).reshape(1000,1000)
# print(data_array)
ruta_npy = os.path.join("res" ,"o_fdata.npy")
np.save(ruta_npy, data_array)


In [70]:
%%timeit # magic function jupyter
with open(ruta_csv,'r') as f:
    data_str = f.read()
data = data_str.split(',')
data_array = np.array(data, dtype = np.int8).reshape(1000,1000)

99.9 ms ± 4.33 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [71]:
%%timeit
data = np.load(ruta_npy)

270 μs ± 6.89 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [95]:
%%timeit # magic function jupyter
result = np.fromfile(ruta_csv, dtype=np.int8, sep=",")

220 ms ± 17.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


<div style="font-family: 'Times New Roman', Times, serif;">
    
#### **8.0.2 Velocidad + simplicidad vs memoria**
#### **8.1 Ejercicios**

1. Imprima la versión numpy y la configuración.
</div>

In [92]:
import numpy as np
# versión de numpy
print("Versión de NumPy:", np.__version__)
# configuración de numpy
np.show_config()

Versión de NumPy: 2.4.0
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-5tdgda_u/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    ope

<div style="font-family: 'Times New Roman', Times, serif;">
    
2. Cómo encontrar el tamaño de la memoria de cualquier matriz
</div>

In [93]:
# crear una matriz
matriz = np.array([[1, 2, 3],[4, 5, 6]])
# tamaño total en bytes
print("Memoria total (bytes):", matriz.nbytes)
# tamaño de cada elemento
print("Bytes por elemento:", matriz.itemsize)
# número total de elementos
print("Número de elementos:", matriz.size)

Memoria total (bytes): 48
Bytes por elemento: 8
Número de elementos: 6


<div style="font-family: 'Times New Roman', Times, serif;">
    
3. Cree un vector nulo de tamaño 10 pero el quinto valor sea 1
</div>

In [94]:
# crear un vector nulo de tamaño 10
vector = np.zeros(10)
# asignar 1 al quinto valor
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


<div style="font-family: 'Times New Roman', Times, serif;">
    
4. Invertir un vector (el primer elemento pasa a ser el último)
</div>

In [95]:
# crear un vector de ejemplo
vector = np.array([1, 2, 3, 4, 5])
# invertir el vector
vector_invertido = vector[::-1]
print(vector_invertido)

[5 4 3 2 1]


<div style="font-family: 'Times New Roman', Times, serif;">
    
5. Encuentre índices de elementos distintos de cero de [1,2,0,0,4,0]
</div>

In [96]:
# crear el vector
vector = np.array([1, 2, 0, 0, 4, 0])
# encontrar índices distintos de cero
indices = np.nonzero(vector)
print(indices)

(array([0, 1, 4]),)


<div style="font-family: 'Times New Roman', Times, serif;">
    
6. Crea una matriz de 3x3x3 con valores aleatorios.
</div>

In [97]:
# crear una matriz 3x3x3 con valores aleatorios
matriz = np.random.rand(3, 3, 3)
print(matriz)

[[[0.18462792 0.71196444 0.81100818]
  [0.62167918 0.1860187  0.19329286]
  [0.92836681 0.2718131  0.08221879]]

 [[0.34632493 0.2691942  0.17807288]
  [0.6596434  0.54495872 0.13238571]
  [0.55915597 0.32327928 0.77592604]]

 [[0.61826017 0.31935002 0.09748694]
  [0.91563705 0.93735086 0.8960542 ]
  [0.75785528 0.81407378 0.29228343]]]


<div style="font-family: 'Times New Roman', Times, serif;">
    
7. Crea un vector aleatorio de tamaño 30 y encuentra el valor medio. 
</div>

In [98]:
# crear un vector aleatorio de tamaño 30
vector = np.random.rand(30)
# calcular el valor medio
media = np.mean(vector)
print("Vector:", vector)
print("Valor medio:", media)

Vector: [0.21214568 0.17377895 0.25013916 0.44836767 0.80124602 0.5644996
 0.07087876 0.71510653 0.11446423 0.83946545 0.34996941 0.40244795
 0.09458203 0.63259245 0.18607598 0.85830565 0.13871623 0.19711417
 0.53327967 0.03666642 0.70235417 0.95771869 0.19829132 0.53170439
 0.04543304 0.88023918 0.66948199 0.79302111 0.45854697 0.97701503]
Valor medio: 0.46112159702580185


<div style="font-family: 'Times New Roman', Times, serif;">
    
8. ¿Cómo agregar un borde (relleno con ceros) alrededor de una matriz existente?
</div>

In [99]:
# matriz original
matriz = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
# agregar un borde de ceros
matriz_con_borde = np.pad(matriz, pad_width=1, mode='constant', constant_values=0)
print(matriz_con_borde)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


<div style="font-family: 'Times New Roman', Times, serif;">
    
9. Crea una matriz de 5x5 con valores 1,2,3,4 justo debajo de la diagonal.
</div>

In [100]:
# valores debajo de la diagonal
valores = [1, 2, 3, 4]
# crear la matriz 5x5
matriz = np.diag(valores, k=-1)
print(matriz)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


<div style="font-family: 'Times New Roman', Times, serif;">
    
10. Considere una matriz de formas (6,7,8), ¿cuál es el índice (x,y,z) del elemento número 100?
</div>

In [101]:
# Convierte el índice plano 100 en un índice tridimensional
# considerando una matriz con forma (6, 7, 8)
indice = np.unravel_index(100, (6, 7, 8))
# Imprime el índice resultante en forma (x, y, z)
print(indice)

(np.int64(1), np.int64(5), np.int64(4))
